**Excel**
=IF(LEFT(E2,2)="\\","SMB", IF(LEFT(E2,7)="SFTP://","SFTP", IF(LEFT(E2,6)="FTP://","FTP", IF(LEFT(E2,3)="E:\","LOCAL",IF(LEFT(E2,8)="SCHEDULE","SCHEDULE", IF (LEFT(E2,2)="S3","S3","EMAIL"))))))

**PowerQuery**
if Text.StartsWith([URI], "\\") then "SMB" 
else if Text.StartsWith([URI], "SFTP://") then "SFTP" 
else if Text.StartsWith([URI], "FTP://") then "FTP" 
else if Text.StartsWith([URI], "E:\") then "LOCAL" 
else if Text.StartsWith([URI], "SCHEDULE") then "SCHEDULE" 
else if Text.StartsWith([URI], "S3") then "S3" 
else "EMAIL"



-----------------------
let
    // Load all tables from current workbook
    Source = Excel.CurrentWorkbook(),

    // Rename the auto-generated Name column to TableName
    #"Renamed Columns" = Table.RenameColumns(Source, {{"Name", "TableName"}}),

    // Filter out any tables named "Summary"
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [TableName] <> "Summary"),

    // Expand the table content to include NAME and URI columns
    #"Expanded Content" = Table.ExpandTableColumn(#"Filtered Rows", "Content", {"NAME", "URI"}, {"NAME", "URI"}),

    // Add calculated column PROTOCOL based on URI value
    #"Added PROTOCOL" = Table.AddColumn(#"Expanded Content", "PROTOCOL", each 
        if Text.StartsWith([URI], "\\") then "SMB" 
        else if Text.StartsWith(Text.Upper([URI]), "SFTP://") then "SFTP" 
        else if Text.StartsWith(Text.Upper([URI]), "FTP://") then "FTP" 
        else if Text.StartsWith(Text.Upper([URI]), "E:\") or Text.StartsWith(Text.Upper([URI]), "E:\\") then "LOCAL" 
        else if Text.StartsWith(Text.Upper([URI]), "SCHEDULE") then "SCHEDULE" 
        else if Text.StartsWith(Text.Upper([URI]), "S3") then "S3" 
        else "EMAIL"
    ),

    // Add TARGET column based on PROTOCOL
    #"Added TARGET" = Table.AddColumn(#"Added PROTOCOL", "TARGET", each 
        if [PROTOCOL] = "SMB" then Text.Split([URI], "\"){2}
        else if [PROTOCOL] = "SFTP" or [PROTOCOL] = "FTP" then
            Text.BeforeDelimiter(
                if Text.Contains(Text.AfterDelimiter([URI], "://"), "@") 
                    then Text.AfterDelimiter([URI], "@") 
                    else Text.AfterDelimiter([URI], "://"),
                if Text.Contains(Text.AfterDelimiter([URI], "://"), ":") then ":" else "/")
        else if [PROTOCOL] = "S3" then Text.Split([URI], "/"){2}
        else null
    ),

    // Reorder columns as desired
    #"Reordered Columns" = Table.ReorderColumns(#"Added TARGET", {"TableName", "NAME", "URI", "PROTOCOL", "TARGET"})
in
    #"Reordered Columns"

--------------------

let
    // Load all tables from current workbook
    Source = Excel.CurrentWorkbook(),

    // Rename the auto-generated Name column to TableName
    #"Renamed Name" = Table.RenameColumns(Source, {{"Name", "TableName"}}),

    // Filter out any tables named "Summary"
    #"Filtered Rows" = Table.SelectRows(#"Renamed Name", each [TableName] <> "Summary"),

    // Expand the table content
    #"Expanded Content" = Table.ExpandTableColumn(
        #"Filtered Rows", 
        "Content", 
        {"PROTO", "VLAN", "HOST_SRC", "IP_SRC", "HOST_DST", "IP_DST", "PORT", "HIT"}, 
        {"PROTO", "VLAN", "HOST_SRC", "IP_SRC", "HOST_DST", "IP_DST", "PORT", "HIT"}
    ),

    // Create a new IP_SRC column with HOST_SRC merged if needed
    #"Updated IP_SRC" = Table.TransformColumns(
        Table.AddColumn(
            #"Expanded Content",
            "IP_SRC_Temp",
            each if Text.Lower(Text.Trim([HOST_SRC])) <> "host" and [HOST_SRC] <> "" 
                 then [HOST_SRC] & " /" & [IP_SRC] 
                 else [IP_SRC],
            type text
        ),
        {"IP_SRC_Temp", each _, type text}  // keep type text
    ),

    // Remove old IP_SRC and rename the new column
    #"Replaced IP_SRC" = Table.RemoveColumns(#"Updated IP_SRC", {"IP_SRC"}),
    #"Renamed IP_SRC" = Table.RenameColumns(#"Replaced IP_SRC", {{"IP_SRC_Temp", "IP_SRC"}}),

    // Blank HOST_SRC
    #"Blanked HOST_SRC" = Table.TransformColumns(#"Renamed IP_SRC", {{"HOST_SRC", each "", type text}}),

    // Reorder columns
    Final = Table.ReorderColumns(
        #"Blanked HOST_SRC", 
        {"TableName", "VLAN", "HOST_SRC", "IP_SRC", "HOST_DST", "IP_DST", "PROTO", "PORT", "HIT"}
    )
in
    Final

----------
